apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning-deployment
  labels:
    app: planning
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planning
  template:
    metadata:
      labels:
        app: planning
    spec:
      containers:
        - name: planning-service
          image: planning-service:latest # Image Docker pour la gestion des planifications
          ports:
            - containerPort: 8083
          env:
            - name: DATABASE_URL
              value: "jdbc:postgresql://db-service:5432/garage"
            - name: DATABASE_USERNAME
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "admin123"
