services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: client_service
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/clientdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "8081:8081"

  db:
    image: postgres
    container_name: client_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=clientdb
    ports:
      - "5432:5432"